version: "3.8"
services: 
  app:     
    build: 
      context: "./src"
    volumes: 
      - "./src:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/php.ini"   
    depends_on: 
      - db-context  
    user: '1000:1000'
  proxy:
    image: nginx:alpine
    volumes: 
      - "./src:/var/www/html"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf" 
      - "./etc/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf"
    ports: 
      - 6007:80
    depends_on: 
      - app
      - db-context
    links:
      - db-context
  db-context:    
    image: mariadb:10.2.40-bionic
    restart: always    
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: s8sw7t3jnsk
      MYSQL_DATABASE: 'funnelnek'
      MYSQL_USER: 'rbanks'
      MYSQL_PASSWORD: 'theking1'
    volumes: 
      - "./etc/mysql/migration/data:/var/lib/mysql"
      - "./etc/mysql/my.cnf:/etc/mysql/my.cnf"
      #- "./etc/mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d"
    ports: 
      - 3307:3306

